<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.eclipse.dltk.javascript</groupId>
        <artifactId>javascript</artifactId>
        <version>5.1.1-SNAPSHOT</version>
    </parent>

    <artifactId>org.eclipse.dltk.javascript.site</artifactId>
    <packaging>eclipse-repository</packaging>
    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-gpg-plugin</artifactId>
                <version>${tycho-version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>sign-p2-artifacts</goal>
                        </goals>
                        <configuration>
                            <signer>bc</signer>
                            <skipIfJarsigned>false</skipIfJarsigned>
                            <keyname>D9DE7716CDB8905A30C8CDEFE15A4758177D4570</keyname>
                            <addPublicKeyToRepo>true</addPublicKeyToRepo>
                            <addPublicKeyToArtifacts>true</addPublicKeyToArtifacts>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>